### ISSUE TITLE
没有找到有关获取计算图片视觉最佳宽高的方法

### ISSUE THREAD

**Issue by J3DFox** [F-loat/mpvue-wxParse#10]
请问目前图片自适应有什么解决方案吗?

**Comment by F-loat** [comment]
这部分代码删掉了，不是太清楚之前是想要达到什么样的效果，提供了一个图片模式的属性，你可以说下你希望的效果，我看下能不能实现

**Comment by J3DFox** [comment]
假设:
当一个image的自定义样式为
`styleStr: "height:1015px; width:1500px"`   
那么mode的属性无论是设置什么都是根据这个宽度来填充或者截取的

下面3个函数就是计算当前屏幕宽度后,重新改变这些image图片的高度宽度
`function wxParseImgLoad(e) `
`function calMoreImageInfo(e, idx, that, bindName) `
`function wxAutoImageCal(originalWidth, originalHeight,that,bindName)`

已经尝试在wxParseImg.vue中加入`@load="wxParseImgLoad"`
并稍微修改上面3个函数.


但是水平有限, 修改props中node相关的值和事件e.target的相关值后, 第一次清缓存加载不成功,切换页面再回来图片就自适应宽度了. ,理论上应该是修改$data来双向绑定高度宽度的值,就可以达到目的.

**Comment by F-loat** [comment]
好的，我有空时试一下，你改的差不多的话可以先提个 pr ，然后我在你的基础上修改就好

**Comment by J3DFox** [comment]
已经pr了, 有空麻烦看下,还需要解决两个问题
一个是在calMoreImageInfo中修改image高度和宽度的方式和在wxAutoImageCal中传入有效的padding

**Comment by F-loat** [comment]
👌格式你有空修改下吧，不然不统一，而且不便于 review，具体内容的我可能得晚上才能仔细看

**Comment by F-loat** [comment]
#11
