### ISSUE TITLE
模板那一块是什么原因没有使用递归

### ISSUE THREAD

**Issue by z008hy** [F-loat/mpvue-wxParse#14]
看到模块那块几个相同文件引用了好几次，是是什么原因没有使用递归

**Comment by F-loat** [comment]
小程序不支持模板递归调用，可以写个脚本自动生成倒是

**Comment by z008hy** [comment]
好的谢谢了，我试了下在mpvue中好像无法使用vue递归

**Comment by F-loat** [comment]
对，因为模板要预先编译出来，估计是没法支持了
