### ISSUE TITLE
wepy中使用报错

### ISSUE THREAD

**Issue by reprover** [F-loat/mpvue-wxParse#16]
...
代码长这样
![image](https://user-images.githubusercontent.com/9566402/39345078-0643f28a-4a19-11e8-8b45-332e2ac15d2c.png)

报错长这样
![image](https://user-images.githubusercontent.com/9566402/39345083-1097a754-4a19-11e8-8c82-0b9d141ec1cb.png)

引入什么的都没问题，貌似是wepy不支持标准的vue语法？

**Comment by reprover** [comment]
sorry 找错地儿了

**Comment by F-loat** [comment]
这个应该是不能直接在 wepy 中使用的，具体的使用方法 wepy 的 issue 里有，不过好像没看到有人做二次封装
