### ISSUE TITLE
能给一个A标签事件处理的例子吗？

### ISSUE THREAD

**Issue by SevenChen** [F-loat/mpvue-wxParse#18]
另外小问题，A标签被转成view后，全部换行了，这个有什么好的办法让其不换行吗，谢谢～

**Comment by F-loat** [comment]
a 标签应该不会换行啊，贴一部分你的富文本我试下，事件处理监听 navigate 事件就好

**Comment by SevenChen** [comment]
<a href='@min=SZ002610' style='color:#2c8ce7;'> 爱康科技</a>（002610）   这是富文本

**Comment by F-loat** [comment]
emm代码能发文本最好就不要发图片

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/40127304-a3045df6-5961-11e8-84d3-c82c52014f1a.png)
不会换行的啊

**Comment by F-loat** [comment]
你是不是没有引入样式文件

**Comment by SevenChen** [comment]
厄。。是没有引入样式，现在好了。

监听 navigate 事件，是监听子组件的事件吗？

**Comment by F-loat** [comment]
``` html
<wxParse :content="article" @navigate="navHandler" />
```

``` js
methods: {
  navHandler (url) {
    console.log(url)  
  }
}
```

**Comment by SevenChen** [comment]
非常感谢～
