### ISSUE TITLE
打开多个富文本之后预览图片问题

### ISSUE THREAD

**Issue by yangchaoy** [F-loat/mpvue-wxParse#19]
大佬有没有遇到这个问题，打开多个富文本之后，当前富文本页面预览图片会出现之前打开的富文本中的图片。例如： 打开了两个富文本,在第三富文本中预览图片会触发三次preview事件，我尝试清除发现都不对，给个思路好么

**Comment by F-loat** [comment]
最新版还有这个问题吗，我有空再试试

**Comment by htfcumt2004** [comment]
最新版还继续有问题额

**Comment by F-loat** [comment]
已经定位到问题了，是 eventBus 的误用导致的，稍后调整下实现方式

**Comment by yangchaoy** [comment]
多谢大佬  回头试下

**Comment by yangchaoy** [comment]
目前的解决是共用一个展示页 ，稍微改了下源码，晚点试试最新版的

**Comment by htfcumt2004** [comment]
今天更新下试试
