### ISSUE TITLE
更改base.config.js之后build和run dev 都报错

### ISSUE THREAD

**Issue by myhuangqiang** [F-loat/mpvue-wxParse#21]
error  in ./~/mpvue-wxparse/src/utils/bus.js
![image](https://user-images.githubusercontent.com/25660665/40639662-a757f40c-6344-11e8-97ab-7d967b9b6105.png)
![image](https://user-images.githubusercontent.com/25660665/40639678-bfd3268c-6344-11e8-95c6-4678a9c5e664.png)

**Comment by F-loat** [comment]
mpvue-loader 更新到 1.0.14 以上的版本即可
