### ISSUE TITLE
运行完build后，并没有效果

### ISSUE THREAD

**Issue by JieChen0712** [F-loat/mpvue-wxParse#22]
只是把它变成这样<view class="_div data-v-3f184284 wxParse"></view>，并没有效果，是我用错了？

**Comment by F-loat** [comment]
？

**Comment by JieChen0712** [comment]
”<view class="_div data-v-5faa7826 wxParse"></view>“，html代码没了。。。，他只是变成一个view，并没有输出文本编辑器的内容

**Comment by JieChen0712** [comment]
view class="_div data-v-5faa7826 wxParse" view   他只是把他编译成view，但是没有把富文本的内容编译出来

**Comment by F-loat** [comment]
dev 模式没问题吗

**Comment by JieChen0712** [comment]
好吧，现在发现是百度编辑器里面的图片显示不了，是自动忽略了？文本是有了

**Comment by F-loat** [comment]
图片没有渲染还是没有显示

**Comment by F-loat** [comment]
图片地址需要有域名才行

**Comment by JieChen0712** [comment]
多谢提醒，百度的编辑器的图片是相对路径所以没显示，加上域名就好了！打扰了！

**Comment by F-loat** [comment]
域名好像有个自动补全的功能，完了我加个属性处理下

**Comment by F-loat** [comment]
v0.6.4 版之后可通过 `imageProp.domain` 设置需要自动补全的图片域名信息

``` pug
wxParse(:content="article", ref="wxParse", :image-prop="{domain: 'eg.domain.com'}")
```
