### ISSUE TITLE
按照官方示例使用报unexpected tag, near `wx-pars...`

### ISSUE THREAD

**Issue by zxrliuyan** [F-loat/mpvue-wxParse#24]
![qq 20180601144725](https://user-images.githubusercontent.com/6167866/40825693-03ad5e8c-65ab-11e8-8072-57dd8762595a.png)

求解！

**Comment by F-loat** [comment]
贴下代码

**Comment by zxrliuyan** [comment]
unexpected tag, near `wx-pars...`
  14 |       <view class="_div data-v-702dfe5c tit">服务详情</view>
  15 |       <view class="_div data-v-702dfe5c cont">
> 16 |         <wx-parse content="{{model.Service_Procedure}}" bindpreview="handleProxy" bindnavigate="handleProxy" data-eventid="{{'0'}}" data-comkey="{{$k}}" class="_wx-parse data-v-702dfe5c"></wx-parse>
     |         ^
  17 |       </view>
  18 |     </view>
  19 |     <view class="_div data-v-702dfe5c contact">

**Comment by zxrliuyan** [comment]
![qq 20180601144621](https://user-images.githubusercontent.com/6167866/40825650-de088c92-65aa-11e8-8e23-39b86be89bd9.png)

**Comment by F-loat** [comment]
你没引入组件吧

**Comment by zxrliuyan** [comment]
![qq 20180601144932](https://user-images.githubusercontent.com/6167866/40825806-4f95a1b0-65ab-11e8-9a60-361ebe14534f.png)

**Comment by F-loat** [comment]
你把 js 部分也贴出来啊。。components 属性里有写吗

**Comment by zxrliuyan** [comment]
感谢大神、是我疏忽了
