### ISSUE TITLE
当<wxParse>的父元素有padding时，图片宽度没有计算padding值

### ISSUE THREAD

**Issue by slime7** [F-loat/mpvue-wxParse#25]
预期效果：
![2](https://user-images.githubusercontent.com/8674371/41140831-3b44cee4-6b22-11e8-97fb-b886487b0f41.png)
实际效果：
![1](https://user-images.githubusercontent.com/8674371/41140836-411c5b20-6b22-11e8-8288-1125f7bd9782.png)

**Comment by slime7** [comment]
刚发现更新后要自行引入样式了，引入后不会超出但是还是没有计算 padding 的。
高度是用屏幕宽度按原比例换算的，样式自带`max-height: 100%`后图片上下就会有白边。
![1](https://user-images.githubusercontent.com/8674371/41141199-a85329d0-6b23-11e8-8b8e-64711cf73e15.png)

**Comment by slime7** [comment]
好的，那只能手动给文字加 padding 了。
其实刚开始以为图片的 padding 是给这个情况解决的。
不过能不能考虑给包裹图片的父容器加个 class 方便处理呢，毕竟内容不一定是我自己编辑的，别人有可能不注意文字的 padding。

**Comment by F-loat** [comment]
你是希望整体都有 padding 吗，那图片的可以通过属性传进入，其他的应该给 p 标签加 padding 属性就可以吧

**Comment by slime7** [comment]
不用整体 padding 的话，文字不是太靠边了，要每个文字部分都自己 padding 了么。
我想如果图片的父元素有 class 的话直接给个负值 margin 让图片单独撑满容器算了。

**Comment by F-loat** [comment]
也不会太靠边吧，p 标签本身是有边距的，你的文本不都是包在 p 标签里的？

**Comment by F-loat** [comment]
图片和其他元素是同级的吧

**Comment by slime7** [comment]
我想了一下，其实我是 markdown 转的，图片都被包进 p 了，好像跟这个插件没啥关系了，应该是 marked 的问题了……

**Comment by F-loat** [comment]
markdown 有直接渲染的办法，你搜一下，比用这个好不少
