### ISSUE TITLE
第二个issuse,关于开发中遇到的问题

### ISSUE THREAD

**Issue by fangdiao** [F-loat/mpvue-wxParse#3]
1. 当富文本较多时，控制台会console出一个超大json对象，影响调试，这个能去掉最好了

2. 建议去掉markdown以及表情部分，因为在小程序中用不到这些，减小体积

**Comment by F-loat** [comment]
第一个已经加了开关了，默认是不输出的，你更新下试试，第二个晚点会改成默认不引入

**Comment by F-loat** [comment]
markdown 及 emoji 已去除，markdown 请使用其他类库先转为 html
