### ISSUE TITLE
编辑器能实现吗？

### ISSUE THREAD

**Issue by skybosi** [F-loat/mpvue-wxParse#30]
Hello：
刚体验你的小程序，确实能在wxparse的基础上实现漂亮的渲染，但是仅仅是渲染，能否实现一个富文本编辑器呢？
提供一些简单的控制按钮，什么加粗，斜体，标题级别，中划线，下划线等等之类的控制工具，在用点击后直接基于wxparse渲染出来了。这个应该是wxparse的更高级的应用！

**Comment by F-loat** [comment]
官方好像要做了😅
