### ISSUE TITLE
报错 Template "2a9d8001" not found.

### ISSUE THREAD

**Issue by LiAo0821** [F-loat/mpvue-wxParse#34]
![image](https://user-images.githubusercontent.com/25658190/43113066-5741884e-8f2b-11e8-9b43-a298a627695b.png)
有人遇到过吗

**Comment by F-loat** [comment]
应该是 mpvue-loader 的版本和打包配置不匹配的问题，https://github.com/Meituan-Dianping/mpvue/issues/795
