### ISSUE TITLE
新版本mpvue引用wxparse无法出现效果,打包生成的dist也有问题,报错如下

### ISSUE THREAD

**Issue by heyushuo** [F-loat/mpvue-wxParse#38]
![1](https://user-images.githubusercontent.com/19450893/43448483-ab357c8e-94e0-11e8-93c2-29c0f5517329.png)
![2](https://user-images.githubusercontent.com/19450893/43448486-ab9abc70-94e0-11e8-9f07-cf0116ad9c47.png)

**Comment by F-loat** [comment]
应该是 mpvue-loader 的问题吧，可以等一阵子再升级新版

**Comment by heyushuo** [comment]
这样啊,能同步升级一下吗?

**Comment by F-loat** [comment]
这个算那边的 bug 吧应该

**Comment by heyushuo** [comment]
那我先用旧版本的mpvue试试,谢谢了
