### ISSUE TITLE
默认打包后会给原始图片添加style的宽度和高度,请问这个如何禁止在img标签添加高度和宽度呢

### ISSUE THREAD

**Issue by heyushuo** [F-loat/mpvue-wxParse#39]
默认打包后会给原始图片添加style的宽度和高度,请问这个如何禁止在img标签添加高度和宽度呢
1.打包前
img标签的style里没有样式
2.打包后
img标签会会多出行内样式

**Comment by F-loat** [comment]
目前这样会有什么问题吗

**Comment by heyushuo** [comment]
会导致view的高度和img的高度不一样,会有缝隙,img的高度计算的都是59.33333333px都会是这样的

**Comment by heyushuo** [comment]
![1](https://user-images.githubusercontent.com/19450893/43529822-ae471014-95de-11e8-9157-a51bf6dcc6ef.png)

**Comment by heyushuo** [comment]
现在在你的源码里对图片的高度进行了取整但是展示出来后,,view总是比view里的图片大几像素,view也是图片撑起来的

**Comment by F-loat** [comment]
可以直接在 css 里加一下，确定有优化的话可以提个 pr，完了我试试看

**Comment by F-loat** [comment]
这个保持现状吧，img 本来就是 inline 元素

**Comment by heyushuo** [comment]
你好能加一下联系方式,问一下关于mpvue的问题吗?我的qq:1007561607
