### ISSUE TITLE
解析渲染完成后如何获得wxParse的高度

### ISSUE THREAD

**Issue by onyz4x** [F-loat/mpvue-wxParse#48]
尝试了一下在updated生命周期里使用wx.createSelectorQuery()方法面获取不到渲染后的高度

**Comment by F-loat** [comment]
暂时 mpvue 里应该没办法准确监听渲染完成，可以加点延时试试

**Comment by onyz4x** [comment]
暂时是用延时去做的

**Comment by F-loat** [comment]
应该没什么其他好办法了
