### ISSUE TITLE
还是关于li的问题

### ISSUE THREAD

**Issue by fangdiao** [F-loat/mpvue-wxParse#5]
圆点还是方的，建议给类`li-circle`加上样式
`vertical-align:4px;border-radius:100%;`

**Comment by F-loat** [comment]
只加这个还是不垂直居中啊，100% 和 50% 效果一样的吧

**Comment by fangdiao** [comment]
0.4.1我这儿的点还是方的。确实要居中的话得自己微调

**Comment by F-loat** [comment]
我的是圆的了，你清下缓存试试

**Comment by fangdiao** [comment]
圆了！真的圆了！谢谢大佬

**Comment by F-loat** [comment]
😂没事
