### ISSUE TITLE
微信小程序问题--invokeWebviewMethod 数据传输长度为 1227297 已经超过最大长度 1048576

### ISSUE THREAD

**Issue by huangche007** [F-loat/mpvue-wxParse#51]
使用该插件对从微信公众号上爬取下来的文章进行加载的时候，出现这个错误invokeWebviewMethod 数据传输长度为 1227297 已经超过最大长度 1048576，想着对整个html结构进行拆分，然后使用多个mpvue-wxparse分段解析显示内容，可是不知道该怎么去对这整个html进行拆分

**Comment by huangche007** [comment]
@F-loat 大佬，能否出来交流下

**Comment by F-loat** [comment]
这个插件版的试过吗 https://github.com/ifanrx/wxParser-plugin ，这个大小的富文本即使能渲染出来，mpvue 版的性能也很差的

**Comment by huangche007** [comment]
@F-loat 主要是公司写小程序使用mpvue这个框架来进行开发，用原生的wxParser或者wxParser-plugin是用不了的。但是用原生的方式写小程序使用wxParser，来解析同一篇微信公众号文章是可以的，但是使用mpvue-wxparser来解析就报上面那个错了

**Comment by F-loat** [comment]
mpvue 可以配合原生组件或插件使用的

**Comment by huangche007** [comment]
@F-loat OK Thx，我还是打算对于文章的详情页采用h5的方式去做，这样不仅到时候对于复杂的文章还是从其他渠道爬取的文章，展示效果都更好，而且性能也会稍好些。

**Comment by F-loat** [comment]
嗯，复杂的富文本还是用 webview 好点
