### ISSUE TITLE
img的src路径中带有'code'会被错误的解析

### ISSUE THREAD

**Issue by nullwu** [F-loat/mpvue-wxParse#6]
引用img标签时，发现图片无法显示，经审查元素检查，可以看到，因为图片路径中带有'code'字符串，被错误的解析了。审查元素的结果如图，代码如下。
![qq 20180324130118](https://user-images.githubusercontent.com/32824912/37860607-b1e2db5e-2f63-11e8-8231-6349e60b6295.png)

```js
<template>
  <div>
    <wxParse :content="article" />
  </div>
</template>
<script>
import wxParse from 'mpvue-wxparse'

export default {
  components: {
    wxParse
  },
  data () {
    return {
      article: "<img src='http://p.funcodeit.com/test/ban1.png'>"
    }
  }
}
</script>
```

**Comment by F-loat** [comment]
不时太确定这个替换是为了什么，先去掉了，你测试下，应该没什么问题

**Comment by nullwu** [comment]
@F-loat 非常感谢~！没问题了，你的处理速度太快了~~~
