### ISSUE TITLE
时好时坏 报这种错 

### ISSUE THREAD

**Issue by lucky1231** [F-loat/mpvue-wxParse#62]
VM20179:1 thirdScriptError
html.replace is not a function;at pages/meetingIntro/main page lifeCycleMethod onReady function
TypeError: html.replace is not a function
    at trimHtml (http://127.0.0.1:11748/appservice/common/vendor.js:99644:6)
    at html2json (http://127.0.0.1:11748/appservice/common/vendor.js:99665:10)
    at VueComponent.nodes (http://127.0.0.1:11748/appservice/pages/meetingIntro/main.js:386:97)
    at Watcher.get (http://127.0.0.1:11748/appservice/common/vendor.js:4549:25)
    at Watcher.evaluate (http://127.0.0.1:11748/appservice/common/vendor.js:4656:21)
    at VueComponent.computedGetter [as nodes] (http://127.0.0.1:11748/appservice/common/vendor.js:4885:17)
    at VueComponent.render (http://127.0.0.1:11748/appservice/pages/meetingIntro/main.js:3777:20)
    at VueComponent.Vue._render (http://127.0.0.1:11748/appservice/common/vendor.js:5699:22)
    at VueComponent.updateComponent (http://127.0.0.1:11748/appservice/common/vendor.js:4219:21)
    at Watcher.get (http://127.0.0.1:11748/appservice/common/vendor.js:4549:25)
console.error @ VM20179:1
errorReport @ WAService.js:3
thirdErrorReport @ WAService.js:3
(anonymous) @ WAService.js:3
(anonymous) @ WAService.js:18
z @ WAService.js:18
(anonymous) @ WAService.js:18
(anonymous) @ WAService.js:18
(anonymous) @ WAService.js:6
e.(anonymous function) @ WAService.js:4
e @ appservice?t=1547101664432:9238
r.registerCallback.t @ appservice?t=1547101664432:9238
l.forEach.t @ appservice?t=1547101664432:9238
(anonymous) @ appservice?t=1547101664432:9238
s.onmessage @ appservice?t=1547101664432:9238
VM20179:1 TypeError: Cannot read property 'componentInstance' of null
    at isPatchable (index.js:4550)
    at patchVnode (index.js:4763)
    at updateChildren (index.js:4673)
    at patchVnode (index.js:4769)
    at updateChildren (index.js:4673)
    at patchVnode (index.js:4769)
    at Vue$3.patch (index.js:4883)
    at Vue$3.patch [as __patch__] (index.js:4958)
    at Vue$3.Vue._update (index.js:2090)
    at Vue$3.updateComponent (index.js:2188)

**Comment by F-loat** [comment]
传入的富文本是什么

**Comment by lucky1231** [comment]
> 传入的富文本是什么

<p>这是一间整洁高档的会议室，很适合用来开会<img class="wscnph" src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/3d96b130c71d844ad77a140871027c32.jpg" data-mce-src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/3d96b130c71d844ad77a140871027c32.jpg"><img class="wscnph" src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/未命名文件.jpg" data-mce-src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/未命名文件.jpg"></p>

**Comment by lucky1231** [comment]
> 传入的富文本是什么

`<p>这是一间整洁高档的会议室，很适合用来开会<img class="wscnph" src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/3d96b130c71d844ad77a140871027c32.jpg" data-mce-src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/3d96b130c71d844ad77a140871027c32.jpg"><img class="wscnph" src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/未命名文件.jpg" data-mce-src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/未命名文件.jpg"></p>`

**Comment by lucky1231** [comment]
> 传入的富文本是什么

<p>这是一间整洁高档的会议室，很适合用来开会<img class="wscnph" src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/3d96b130c71d844ad77a140871027c32.jpg" data-mce-src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/3d96b130c71d844ad77a140871027c32.jpg"><img class="wscnph" src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/未命名文件.jpg" data-mce-src="http://kuka-life.oss-cn-hangzhou.aliyuncs.com/pos/jpg/未命名文件.jpg"></p>

**Comment by lucky1231** [comment]
> VM20179:1 thirdScriptError
> html.replace is not a function;at pages/meetingIntro/main page lifeCycleMethod onReady function
> TypeError: html.replace is not a function
> at trimHtml (http://127.0.0.1:11748/appservice/common/vendor.js:99644:6)
> at html2json (http://127.0.0.1:11748/appservice/common/vendor.js:99665:10)
> at VueComponent.nodes (http://127.0.0.1:11748/appservice/pages/meetingIntro/main.js:386:97)
> at Watcher.get (http://127.0.0.1:11748/appservice/common/vendor.js:4549:25)
> at Watcher.evaluate (http://127.0.0.1:11748/appservice/common/vendor.js:4656:21)
> at VueComponent.computedGetter [as nodes] (http://127.0.0.1:11748/appservice/common/vendor.js:4885:17)
> at VueComponent.render (http://127.0.0.1:11748/appservice/pages/meetingIntro/main.js:3777:20)
> at VueComponent.Vue._render (http://127.0.0.1:11748/appservice/common/vendor.js:5699:22)
> at VueComponent.updateComponent (http://127.0.0.1:11748/appservice/common/vendor.js:4219:21)
> at Watcher.get (http://127.0.0.1:11748/appservice/common/vendor.js:4549:25)
> console.error @ VM20179:1
> errorReport @ WAService.js:3
> thirdErrorReport @ WAService.js:3
> (anonymous) @ WAService.js:3
> (anonymous) @ WAService.js:18
> z @ WAService.js:18
> (anonymous) @ WAService.js:18
> (anonymous) @ WAService.js:18
> (anonymous) @ WAService.js:6
> e.(anonymous function) @ WAService.js:4
> e @ appservice?t=1547101664432:9238
> r.registerCallback.t @ appservice?t=1547101664432:9238
> l.forEach.t @ appservice?t=1547101664432:9238
> (anonymous) @ appservice?t=1547101664432:9238
> s.onmessage @ appservice?t=1547101664432:9238
> VM20179:1 TypeError: Cannot read property 'componentInstance' of null
> at isPatchable (index.js:4550)
> at patchVnode (index.js:4763)
> at updateChildren (index.js:4673)
> at patchVnode (index.js:4769)
> at updateChildren (index.js:4673)
> at patchVnode (index.js:4769)
> at Vue$3.patch (index.js:4883)
> at Vue$3.patch [as **patch**] (index.js:4958)
> at Vue$3.Vue._update (index.js:2090)
> at Vue$3.updateComponent (index.js:2188)
