### ISSUE TITLE
希望加入这些功能

### ISSUE THREAD

**Issue by fangdiao** [F-loat/mpvue-wxParse#7]
1. 标签内data开头的字段，希望字段后的内容能得到完全还原，到小程序内通过event.tagrget.dataset可以拿到。

2. a标签内的href属性，希望可以转成data-href，这样可以通过自定义函数做到仿点击超链接。

3. image标签，希望自定义mode属性

**Comment by F-loat** [comment]
第一个具体是指什么啊，a 标签的 属性改了，但是绑事件好像还不行，imageMode 之前就支持的

**Comment by fangdiao** [comment]
我的意思是把a标签的href属性提出来，做成data-href这种，然后我给整个富文本绑一个点击事件，判断是否我是href，模拟点击事件

**Comment by F-loat** [comment]
这不是第二点吗，已经修改了

**Comment by F-loat** [comment]
我试了下，小程序里好像没法获取到被点击的元素是哪个

**Comment by fangdiao** [comment]
可以获得dataset里面的字段，判断是否有herf属性

**Comment by F-loat** [comment]
你的事件绑定在哪个元素上返回的就是哪个元素的 data 属性吧

**Comment by fangdiao** [comment]
对，我的意思是元素本身有data属性的，也给它保留下来

**Comment by F-loat** [comment]
这个不太可能，data 属性本身就是自定义的，而且模板里只能动态设置属性值

**Comment by fangdiao** [comment]
好的，谢谢大佬

**Comment by F-loat** [comment]
@fangdiao 可以通过在父节点上绑个事件取到被点击节点的值，保存在 e.target.dataset 里，之前是因为文本节点多套了一层标签所以拿不到，修正了已经

**Comment by fangdiao** [comment]
好的，谢谢大佬
