### ISSUE TITLE
HTML代码里带转义符要如何处理？

### ISSUE THREAD

**Issue by hooray** [F-loat/mpvue-wxParse#70]
富文本的 HTML 代码通过 api 接口返回 json 数据，双引号会被加上 `\` 转义符，类似这样：
```
{"content":"<h1 style=\"text-align: center;\">TITLE<\/h1>"}
```
这时候 wxParse 就无法解析了，有什么处理办法么？

**Comment by F-loat** [comment]
测试了下是可以解析的，可以用 examples 目录中的示例试下
