### ISSUE TITLE
 - - 我又来提需求了

### ISSUE THREAD

**Issue by fangdiao** [F-loat/mpvue-wxParse#8]
请问能否给a标签下的所有子元素都加上data-href标签，因为在小程序中无法拿到祖先元素的节点属性。
像这样点击子元素或者子孙元素拿不到祖先元素的data-href属性
`<view data-href='something'>
    <view>我是子元素</view>
    <view>
       <view>我是子孙元素</view>
    </view>
</view>`

**Comment by F-loat** [comment]
我其实也有发现这个问题，但是感觉这么处理也不太好

**Comment by fangdiao** [comment]
现在也只能这样吧，能不能先就这样改，后面有好的解决办法在上其他的方案？

**Comment by fangdiao** [comment]
a标签里面可能还有a标签，当遇到下个a标签的时候，后面的子孙元素使用最近的祖先a标签的herf属性，依次类推

**Comment by F-loat** [comment]
我考虑下

**Comment by F-loat** [comment]
这个暂时还是不做处理
