### ISSUE TITLE
图片设置宽度不考虑设置边距的情况么

### ISSUE THREAD

**Issue by daialihexiaoniu** [F-loat/mpvue-wxParse#82]
图片设置宽度不考虑设置边距的情况么，图片外层容器设置了边距之后，图片的大小仍然是屏幕大小

**Comment by qiyian** [comment]
请问怎么解决的？

**Comment by qiyian** [comment]
> 图片设置宽度不考虑设置边距的情况么，图片外层容器设置了边距之后，图片的大小仍然是屏幕大小

请问怎么解决的？
