### ISSUE TITLE
新版微信开发者工具会警告

### ISSUE THREAD

**Issue by begonia9193** [F-loat/mpvue-wxParse#91]
wx:key="node.index" does not look like a valid key name (did you mean wx:key="index" ?)
来源于微信官方，好像wx:for 中的wx:key 的用法改变了

**Comment by hongxb** [comment]
没人解决吗

**Comment by begonia9193** [comment]
> 没人解决吗

我jio的还是copy一份自己维护吧，这个库可能已经没人管了

**Comment by F-loat** [comment]
最近解决下，确实没怎么维护了，而且这个库本身实现原理不算太好，不是很推荐使用了

可以试下 [jin-yufeng/Parser](https://jin-yufeng.github.io/Parser/#/instructions?id=%e5%9c%a8-mpvue-%e4%b8%ad%e4%bd%bf%e7%94%a8)
